title: Andre Leiradella
description: Generalist Programmer
author: Andre Leiradella
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
email: andre@leiradella.com
twitter_username: leiradel
github_username: leiradel
