title: Andre Leiradella
description: Generalist Programmer
author: Andre Leiradella
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
email: printf("%s@%s.com", "andre", "leiradella");
twitter_username: leiradel
github_username: leiradel
